name: Upload IaC to S3

on:
  push:
    branches:
      - main
    paths:
      - "iac/base-infra-cfn.yaml"
  pull_request:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ODIC }}
          aws-region: us-east-2

      # - name: Validate CFN template
      #   run: |

      # - name: Copy files to S3 bucket
      #   run: |
      #     aws s3 sync iac/base-infra-cfn.yaml s3://
